### ISSUE TITLE
Outdated links from transferring repository to new organization

### ISSUE THREAD

**Issue by vfscalfani** [UA-Libraries-Research-Data-Services/UALIB_ScholarlyAPI_Cookbook#62]
Here is an initial list of links that need to be updated from @MoenMi 

- The link to the ROR recipe within the OpenAlex recipe
- The link to the GeoNames recipe within the NWS recipe
- Links in the license page, and the readme of the GitHub repo
- The link to the workshops repo in the introduction page of the cookbook
- The link to the cookbook in the config YAML file

Thanks, Vin

**Comment by AveryUALibrary** [comment]
Should be fixed by https://github.com/UA-Libraries-Research-Data-Services/UALIB_ScholarlyAPI_Cookbook/pull/63
